JOB_STATUS_QUEUED = "queued"
JOB_STATUS_SCHEDULED = "scheduled"
JOB_STATUS_CLAIMED = "claimed"
JOB_STATUS_RUNNING = "running"
JOB_STATUS_COMPLETED = "completed"
JOB_STATUS_FAILED = "failed"
JOB_STATUS_RETRY = "retry"
JOB_STATUS_CANCELLED = "cancelled"
JOB_STATUS_DEAD_LETTER = "dead_letter"

TERMINAL_JOB_STATUSES = {
    JOB_STATUS_COMPLETED,
    JOB_STATUS_CANCELLED,
    JOB_STATUS_DEAD_LETTER,
}

CLAIMABLE_JOB_STATUSES = {JOB_STATUS_QUEUED, JOB_STATUS_RETRY}

WORKER_STATUS_STARTING = "starting"
WORKER_STATUS_IDLE = "idle"
WORKER_STATUS_BUSY = "busy"
WORKER_STATUS_DRAINING = "draining"
WORKER_STATUS_STOPPED = "stopped"

RETRY_STRATEGY_FIXED = "fixed"
RETRY_STRATEGY_LINEAR = "linear"
RETRY_STRATEGY_EXPONENTIAL = "exponential"
RETRY_STRATEGY_CUSTOM = "custom"

SCHEDULE_TYPE_DELAY = "delay"
SCHEDULE_TYPE_CRON = "cron"
SCHEDULE_TYPE_RECURRING = "recurring"

REDIS_STREAM_PREFIX = "queue:notify:"
REDIS_PUBSUB_CHANNEL = "scheduler:events"
