"""add unique constraint on queue project_id+name

Revision ID: fedb1b1c0fe7
Revises: d2261f31d037
Create Date: 2026-07-05 12:11:53.228160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fedb1b1c0fe7'
down_revision: Union[str, Sequence[str], None] = 'd2261f31d037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_project_queue_name', 'queues', ['project_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_queue_name', 'queues', type_='unique')
    # ### end Alembic commands ###
